on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        # scp -o StrictHostKeyChecking=no -r ./* ec2-user@your-ec2-ip:/home/ec2-user/your-app-directory/
        scp -o StrictHostKeyChecking=no ./*.py ec2-54-227-16-110.compute-1.amazonaws.com:/home/ec2-user/rnn-ner-api/

    - name: Install dependencies on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-54-227-16-110.compute-1.amazonaws.com << 'EOF'
          cd /home/ec2-user/rnn-ner-api/
          # pip3 install -r requirements.txt
          sudo systemctl restart gunicorn.service
        EOF
