name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy app to EC2
      run: |
        # scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.DNS }}:/home/ec2-user/rnn-ner-api/
        scp -o StrictHostKeyChecking=no ./*.py ${{ secrets.DNS }}:/home/ec2-user/rnn-ner-api/

    - name: Install dependencies on EC2 and restart gunicorn
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DNS }} << 'EOF'
          cd /home/ec2-user/rnn-ner-api/
          pip3 install -r requirements.txt
          sudo systemctl restart gunicorn.service
        EOF
